### ISSUE TITLE
Not compatible with modern Ruby

### ISSUE THREAD

**Issue by chrisseaton** [blambeau/viiite#6]
```
% ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
```

```ruby
Viiite.bench do |r|
  n = 15000
  r.report(:for)   { for i in 1..n; a = "1"; end }
  r.report(:times) { n.times do   ; a = "1"; end }
  r.report(:upto)  { 1.upto(n) do ; a = "1"; end }
end
```

```
% viiite report bug.rb            
/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf/operator/class_methods.rb:97:in `new': tried to create Proc object without a block (ArgumentError)
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf/operator/class_methods.rb:97:in `signature'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf/operator/non_relational/autonum.rb:6:in `<class:Autonum>'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf/operator/non_relational/autonum.rb:3:in `<module:NonRelational>'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf/operator/non_relational/autonum.rb:2:in `<module:Alf>'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf/operator/non_relational/autonum.rb:1:in `<top (required)>'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf.rb:244:in `<module:NonRelational>'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf.rb:243:in `<module:Operator>'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf.rb:216:in `<module:Alf>'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/alf-0.10.1/lib/alf.rb:15:in `<top (required)>'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/viiite-0.2.0/lib/viiite/loader.rb:1:in `<top (required)>'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/viiite-0.2.0/lib/viiite.rb:5:in `<top (required)>'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/viiite-0.2.0/bin/viiite:3:in `<top (required)>'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/bin/viiite:25:in `load'
        from /Users/chrisseaton/.rbenv/versions/3.1.2/bin/viiite:25:in `<main>'
```

From https://github.com/msgpack/msgpack-ruby/pull/288#issuecomment-1184349455.

**Comment by eregon** [comment]
Ah so it's an issue of `alf`, cc @blambeau

**Comment by blambeau** [comment]
Viiite is unfortunately no longer maintained (neither is Alf).

I think there are many good alternatives for benchmarking these days. WDYT?

**Comment by eregon** [comment]
Yes, I think for most use cases benchmark-ips is fine.

Alf is a different story, are there any alternatives?

**Comment by blambeau** [comment]
Alf was an academic experiment. The ambition was too large, and the code base not great enough. I was not comfortable putting in production.

So I started the successor https://github.com/enspirit/bmg.

Single gem, no command line, no core extension, SQL compilation with less bugs, more pragmatic, less pure.
